api_platform:
    title: MyBookings API
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    show_webby: false
    enable_entrypoint: false
    enable_docs: false
    serializer:
        hydra_prefix: false
    defaults:
        pagination_enabled: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: false
        extra_properties:
            standard_put: true
    use_symfony_listeners: true

when@prod:
    api_platform:
        enable_swagger: false
        enable_swagger_ui: false
        enable_docs: true
        enable_entrypoint: false

when@dev:
    api_platform:
        enable_entrypoint: true
        enable_docs: true